version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - ${SERVER_PORT}:80
    container_name: ${CONTAINER_PREFIX}-nginx

  app:
    build:
      context: .
      args:
        - tag=${PHP_TAG}
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    depends_on:
      - nginx
      - db
    container_name: ${CONTAINER_PREFIX}-php-fpm

  db:
    image: mysql:${DB_VERSION}
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./docker/mysql/db/:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    container_name: ${CONTAINER_PREFIX}-db

  # redis:
  #   image: redis:alpine
  #   command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
  #   volumes:
  #     - ./docker/redis:/data
  #   ports:
  #     - ${REDIS_PORT}:6379
